### ISSUE TITLE
different users with different credit rate

### ISSUE THREAD

**Issue by alialkaner** [playsms/playsms#150]
1. admin can define different credit sets
2. admin can assign credit set to different users

**Comment by macmaina** [comment]
Please advice if this was completed on the current version. "different users with different credit rate"

**Comment by alialkaner** [comment]
You need to add credit to users not money :) Credit rate default 1 . Sample  Add 1000 credit 1000$ :) .  You must remove the dollar symbol. Users should be able to see the sms credit not money.

**Comment by MrVitorF** [comment]
###Love your work, congrats.
This option would really be great.
Also, maybe set nr of sms client can send, regardless of balance.
Like, client buys sms package of 100 SMS
Thanks, you rock

**Comment by astrakid** [comment]
simply use rate of 1, so each credit is an sms!

**Comment by antonraharja** [comment]
fixed in https://github.com/playsms/playsms/commit/75ba882faa8879e830c46de4beec5d237c65e223
