### ISSUE TITLE
Install script should check and notify about all dependencies

### ISSUE THREAD

**Issue by knightsamar** [playsms/playsms#397]
The installation script `install-playsms.sh` should check and notify the status of all dependencies that playSMS requires. A bonus would be showing distro-specific steps as to how to install these dependencies. 

This would save a lot of time and effort in trying to figure out what is the problem when running playSMS for the first time.

**Comment by antonraharja** [comment]
starts from playSMS 1.4.4-beta3 install script checks most dependencies
