### ISSUE TITLE
faster phonebook import

### ISSUE THREAD

**Issue by antonraharja** [playsms/playsms#441]
now on my laptop import took about 800 records/minutes

**Comment by yosef454** [comment]
I uploaded a  CSV file with 12,000 recipients, and it took only 5,000 recipients.
There is a limit of 5,000 recipients in import one?

**Comment by antonraharja** [comment]
please discuss in user forum

**Comment by antonraharja** [comment]
related to https://github.com/playsms/playsms/commit/5a1b0a2a81ee917d6be0c356bfa3d558b42d9a47
phonebook will adopt this way, closing the issue for now
