### ISSUE TITLE
addslashes

### ISSUE THREAD

**Issue by quiricada** [playsms/playsms#581]
message with apostrophe (') in the message body is inserted into tblRecvSMS but not inserted into tblSMSInbox and tblSMSIncoming

i added
addslashes($message)
prior to the $db_query INSERT statement in function recvsms_inbox_add and recvsms_process

**Comment by antonraharja** [comment]
fixed in https://github.com/playsms/playsms/commit/9325d3c7d9fd4e81a730aa050c497f8f04ff9f87
