### ISSUE TITLE
Queries execution time grows up on highload

### ISSUE THREAD

**Issue by ramil8090** [playsms/playsms#625]
Hi Anton

First of all let me thank you for your awesome playsms!

I try to scale up playsms by starting playsmsd on multiple servers. They all connect to the same database. After starting Apache JMeter to check throughput, queries execution time grow up to 6 seconds. There are many simple queries in mysql_slow.log. For example, SELECT * FROM playsms_tblSMSOutgoing WHERE p_status='0' AND p_smsc='blocked' AND flag_deleted='0'. All this fields have indexes.

Please help me fix this issue! I want to handle about 100 sms per second, but for now it handles only about 15 sms per second.

**Comment by antonraharja** [comment]
Until we can find the specific issue, please continue in Forum instead. Thx.
