### ISSUE TITLE
Empty sent messages in web

### ISSUE THREAD

**Issue by neoscopio** [playsms/playsms#627]
Hi, 
We're testing the dev version (master) and successfully configured a Jasmin gateway. Messages are received, credit deducted, but no messages show in user_outgoing and all_outgoing (My sent messages, All messages). 

The user report "app=main&inc=feature_report&route=user" shows the correct count of sent messages.

I'm guessing a problem with Jasmin gateway module, but no errors in log. Can you help?

> - - 2021-03-07 23:11:47 PID60455db2e2786 - L3 jasmin_hook_sendsms # enter smsc:jasmin smslog_id:2 uid:1 to:XXXXXX
> - - 2021-03-07 23:11:47 PID60455db2e2786 - L3 jasmin_hook_sendsms # send url:[http://XXXX:PPPP/send?username=xxx&password=xxx&to=xxx&from=xxx&content=XXXmeXX%21&dlr=yes&dlr-level=1&dlr-url=http%3A%2F%2Fxxx.xxx.com%2Fxxxsms%2Findex.php%3Fapp%3Dcall%26amp%3Bcat%3Dgateway%26amp%3Bplugin%3Djasmin%26amp%3Baccess%3Dcallback]
> - - 2021-03-07 23:11:47 PID60455db2e2786 - L2 jasmin_hook_sendsms # sent smslog_id:2 message_id:2ba79985-812d-422d-b5a7-5a62c023152c smsc:jasmin
> - - 2021-03-07 23:11:47 PID60455db2e2786 - L3 dlr # isdlrd:1 smslog_id:2 p_status:1 uid:1
> - - 2021-03-07 23:11:47 PID60455db2e2786 - L2 simplerate_hook_rate_deduct # enter smslog_id:2
> - - 2021-03-07 23:11:47 PID60455db2e2786 - L3 simplerate_hook_rate_getbyprefix # rate not found to:xxxxx default_rate:1 uid:1
> - - 2021-03-07 23:11:47 PID60455db2e2786 - L3 simplerate_hook_rate_getcharges # uid:1 u:admin len:24 unicode:0 to:351966913513 enable_credit_unicode:0 count:1 rate:1 charge:1
> - - 2021-03-07 23:11:47 PID60455db2e2786 - L3 simplebilling_hook_billing_post # saving smslog_id:2 parent_uid:0 uid:1 rate:1 count:1 charge:1
> - - 2021-03-07 23:11:47 PID60455db2e2786 - L3 simplebilling_hook_billing_post # saved smslog_id:2 id:2
> - - 2021-03-07 23:11:47 PID60455db2e2786 - L3 simplerate_hook_rate_deduct # deduct successful uid:1 parent_uid:0 smslog_id:2
> - - 2021-03-07 23:11:47 PID60455db2e2786 - L2 sendsms_process # end
> - - 2021-03-07 23:11:47 PID60455db2e2786 - L2 sendsms_daemon # result queue_code:e191cb71b60cf6df936804fa172f5be0 to:351966913513 flag:1 smslog_id:2
> 1.2.3.4 xx.xxxx.com 2021-03-07 23:11:47 PID60455db33b1ec - L2 init # WARNING: possible CSRF attack. sid:cbkn4os0cfm4dh27qg43bl94lb ip:11.22.33.44
> - - 2021-03-07 23:11:47 PID60455db2e2786 - L2 sendsms_daemon # finish processing queue_code:e191cb71b60cf6df936804fa172f5be0 uid:1 sender_id:test queue_count:1 sms_count:1
> - - 2021-03-07 23:11:47 PID60455db2e2786 - L3 playsmsd_once # finish command:sendqueue param:Q_e191cb71b60cf6df936804fa172f5be0_1
> - - 2021-03-07 23:11:48 PID604559873a4ab - L3 dlr_update # smslog_id:2 p_status:1 uid:1
> - - 2021-03-07 23:11:48 PID604559873a4ab - L2 simplebilling_hook_billing_finalize # saving smslog_id:2
> - - 2021-03-07 23:11:48 PID604559873a4ab - L3 simplebilling_hook_billing_finalize # saved smslog_id:2

**Comment by antonraharja** [comment]
Hi,

Please post this in Forum instead.

anton

**Comment by neoscopio** [comment]
done
