### ISSUE TITLE
PlaySMS Asterisk Gateway.

### ISSUE THREAD

**Issue by guyt101z** [playsms/playsms#66]
Asterisk has a very neat setup to send SMS using chan_dongle.  something like ( asterisk -rx 'dongle sms <device> <message> ) can send a sms message. Asterisk manager can be used also. What would it take to  create a custom gateway that can access a bash,php,python,perl script which can use asterisk as a gateway. 

 A feature to have a custom gateway using webservices would work to access asterisk manager also but I cannot see an option to use Webservices as a gateway. I need the "send from file" feature and a custom gateway feature to connect to asterisk.

**Comment by julianobarbosa** [comment]
@antonraharja 

Is possible you guide how to configure new module based on gammu or kannel for chan_dongle on asterisk ?

**Comment by pedrosomiami** [comment]
Hi,

I have this ( Commercial ) working plugin for chan dongle and playsms:

https://www.youtube.com/playlist?list=PLTBA4jVMXBdcWGF401Wpg4t6Nu1ZIDHiK

The system is based on scripts to self install asterisk and chan_dongle.  Working to send and receice sms, you can define diferent routes for each client. If you are in brazil is possible to check destination number carrie and use portabilidade before sending.

Is possible to define a random time to wait before send the next message.

Add skype for more details: pbSYS.com.br.

Thank you,

Pedroso
